### ISSUE TITLE
レビューについて

### ISSUE THREAD

**Issue by MatchaChoco010** [UTokyo-SDP/ex-02-g19-11#6]
レビューは今日の時間内に完成しなかったグループは無しとなりました。
エクササイズ2に関してはレビューをする必要はないようです。

**Comment by GandT** [comment]
確認いたしました。ありがとうございます。

今週は論文投稿の後に体調を崩してしまいこちらの課題に取り組むことができませんでした。
そちらで作っていただいたプルリクエストのマージまではおこなったため、
そちら側で可能だった課題はすべて終わったという評価にはなるかと思います。
